yes | ~/Desktop/iMessageDebug | grep -i -w Model | awk '{print "Model:" $2}'
yes | ~/Desktop/iMessageDebug | grep -i -w Board-id | awk '{print "Board-id:"$2}'
yes | ~/Desktop/iMessageDebug | grep -i -w ROM | awk '{print "ROM:"$2}'
yes | ~/Desktop/iMessageDebug | grep -i -w BoardSerialNumber | awk '{print "BoardSerialNumber:"$2}'
yes | ~/Desktop/iMessageDebug | grep -i -w System-ID | awk '{print "System-ID:"$2}'